package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*MountPropagation A propagation mode for a mount

swagger:model MountPropagation
*/
type MountPropagation string
