package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*MountPoint A mount point inside a container

swagger:model MountPoint
*/
type MountPoint struct {

	/* destination

	Required: true
	*/
	Destination string `json:"Destination"`

	/* driver
	 */
	Driver string `json:"Driver,omitempty"`

	/* mode

	Required: true
	*/
	Mode string `json:"Mode"`

	/* name
	 */
	Name string `json:"Name,omitempty"`

	/* propagation

	Required: true
	*/
	Propagation MountPropagation `json:"Propagation"`

	/* r w

	Required: true
	*/
	RW bool `json:"RW"`

	/* source

	Required: true
	*/
	Source string `json:"Source"`

	/* type
	 */
	Type MountType `json:"Type,omitempty"`
}
