#!/bin/bash
#
# Run all validation (except for vendor, it's slow)

export SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $SCRIPTDIR/dco
. $SCRIPTDIR/default-seccomp
. $SCRIPTDIR/gofmt
. $SCRIPTDIR/lint
. $SCRIPTDIR/pkg-imports
. $SCRIPTDIR/test-imports
. $SCRIPTDIR/toml
. $SCRIPTDIR/vet
