package image

// ----------------------------------------------------------------------------
// DO NOT EDIT THIS FILE
// This file was generated by `swagger generate operation`
//
// See hack/swagger-gen.sh
// ----------------------------------------------------------------------------

// ImageHistoryResponse image history response
// swagger:model ImageHistoryResponse
type ImageHistoryResponse struct {

	// comment
	Comment string `json:"Comment,omitempty"`

	// created
	Created int64 `json:"Created,omitempty"`

	// created by
	CreatedBy string `json:"CreatedBy,omitempty"`

	// Id
	ID string `json:"Id,omitempty"`

	// size
	Size int64 `json:"Size,omitempty"`

	// tags
	Tags []string `json:"Tags,omitempty"`
}
